### ISSUE TITLE
Dubbele background image hover

### ISSUE THREAD

**Issue by Anna-Kyra** [Einanas/the-startup-S6#15]
![20240123_155117](https://github.com/Einanas/the-startup-S6/assets/144000242/9ce28456-79a3-420e-83ca-db7d294f4408)

```CSS
/* Anne */
.image-container0 {
  background-image: url(../ai-assets/fallback.jpeg);
}

.image-container0 .img span {
  background-image: url(../assets/anne.jpg);
}

.content-wrapper0 {
  background-image: url(../ai-assets/fallback.jpeg);
}
```
[Permalink](https://github.com/Einanas/the-startup-S6/blob/8760099d328d8c3eafc904800d0a2e6f8a7b1c98/styles/style.css#L190-L192)

Bij de hover animatie is de ai image twee keer te zien (een zweeft naar boven). 
Ik zie dat `.image-container0` en `.content-wrapper` dezelfde bg-image hebben. De `.content-wrapper` kan weg en dan is het probleem hopelijk gefixed :), maar dan blijft de ai-afbeelding wel statisch staan. Alleen de text komt dan omhoog als je snapt wat ik bedoel
